import { storyblokInit, apiPlugin } from "@storyblok/react/rsc";
import StoryblokProvider from "@/components/context/StoryblokProvider";
import { StoryBlokComponents } from "@/utils/StoryBlokComponents";
import "./globals.css";

export const metadata = {
  title: "Headless Site",
  description: "Generated by create next app",
};

storyblokInit({
  accessToken: process.env.NEXT_PUBLIC_SB_PREVIEW_TOKEN,
  use: [apiPlugin],
  components: StoryBlokComponents,
  apiOptions: {
    region: "us"
  },
});

export default function RootLayout({ children }) {
  return (
    <StoryblokProvider>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </StoryblokProvider>
  );
}
